from tkinter import *
import Documentation

def f1():
    Documentation.submit(e1a.get(),e2a.get(),e3a.get(),e4a.get(),e5a.get(),e6a.get(),e7a.get(),e8a.get(),e9a.get(),e10a.get(),e11a.get())
    window.destroy()

def f2():
    e1.delete(0,'end')
    e2.delete(0,'end')
    e3.delete(0,'end')
    e4.delete(0,'end')
    e5.delete(0,'end')
    e6.delete(0,'end')
    e7.delete(0,'end')
    e8.delete(0,'end')
    e9.delete(0,'end')
    e10.delete(0,'end')
    e11a.delete(0,'end')
    
window=Tk()
window.title("School Leaving Form")

l=Label(window,text="School Leaving Form Fillup",font=("Arial","30"))
l.grid(row=0,column=0,columnspan=2)

e1a=StringVar()
e1=Entry(window,text=e1a,font=("Arial","18"))
e1.grid(row=1,column=1,padx=10)
l1=Label(window,text="Name of School",font=("Arial","18"))
l1.grid(row=1,column=0)
e2a=StringVar()
e2=Entry(window,text=e2a,font=("Arial","18"))
e2.grid(row=2,column=1,padx=10)
l2=Label(window,text="Name of the Road",font=("Arial","18"))
l2.grid(row=2,column=0)
e3a=StringVar()
e3=Entry(window,text=e3a,font=("Arial","18"))
e3.grid(row=3,column=1,padx=10)
l3=Label(window,text="City/District",font=("Arial","18"))
l3.grid(row=3,column=0)
e4a=StringVar()
e4=Entry(window,text=e4a,font=("Arial","18"))
e4.grid(row=4,column=1,padx=10)
l4=Label(window,text="Pincode",font=("Arial","18"))
l4.grid(row=4,column=0)
e5a=StringVar()
e5=Entry(window,text=e5a,font=("Arial","18"))
e5.grid(row=5,column=1,padx=10)
l5=Label(window,text="Name of Student",font=("Arial","18"))
l5.grid(row=5,column=0)
e6a=StringVar()
e6=Entry(window,text=e6a,font=("Arial","18"))
e6.grid(row=6,column=1,padx=10)
l6=Label(window,text="Admission Number of Student",font=("Arial","18"))
l6.grid(row=6,column=0)
e7a=StringVar()
e7=Entry(window,text=e7a,font=("Arial","18"))
e7.grid(row=7,column=1,padx=10)
l7=Label(window,text="Gender of Student",font=("Arial","18"))
l7.grid(row=7,column=0)
e8a=StringVar()
e8=Entry(window,text=e8a,font=("Arial","18"))
e8.grid(row=8,column=1,padx=10)
l8=Label(window,text="Nationality",font=("Arial","18"))
l8.grid(row=8,column=0)
e9a=StringVar()
e9=Entry(window,text=e9a,font=("Arial","18"))
e9.grid(row=9,column=1,padx=10)
l9=Label(window,text="Date of Birth",font=("Arial","18"))
l9.grid(row=9,column=0)
e10a=StringVar()
e10=Entry(window,text=e10a,font=("Arial","18"))
e10.grid(row=10,column=1,padx=10)
l10=Label(window,text="Date of Leaving School",font=("Arial","18"))
l10.grid(row=10,column=0)
e11a=StringVar()
e11=Entry(window,text=e11a,font=("Arial","18"))
e11.grid(row=11,column=1,padx=10)
l11=Label(window,text="Remarks",font=("Arial","18"))
l11.grid(row=11,column=0)

B1=Button(window,text="Clear",font=("Arial","15"),width=20,command=f2)
B1.grid(row=12,column=0,padx=10,pady=10)

B2=Button(window,text="Submit",font=("Arial","15"),width=20,command=f1)
B2.grid(row=12,column=1,padx=10,pady=10)


window.mainloop()